language: python
python: 3.8
sudo: false
branches:
    only:
        - master
        - /^\d\.\d+$/

env:
    - TOXENV=py36
    - TOXENV=py38

install:
    - pip install -U pip tox codecov

script: tox

after_success:
    - codecov

cache:
    directories:
        - $HOME/.cache/pip
